name: Collect Weather Data

on:
  schedule:
    # Runs at 8 AM UTC every day
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  collect:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: pip install requests
      
    - name: Run data collection script
      run: python weather_collector.py
      env:
        WEATHER_API_KEY: ${{ 7add9cf5aa00418a91161932251709 }}
      
    - name: Commit and push if data changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data.json
        git diff --cached --quiet || git commit -m "Update weather data - $(date +'%Y-%m-%d %H:%M')"
        git push
